### ISSUE TITLE
HOME - Quitar un poco de padding/margin top del navbar para que el espacio blanco debajo del navbar visualmente se vea igual que la parte de arriba

### ISSUE THREAD

**Issue by narcisonunez** [AxelCreations/Shopy-Template#11]

**Comment by AxelCreations** [comment]
Estos Espacios fueron configurados según la presentacion del Template Home.psd. Favor revisar y confirmar nuevamente....

**Comment by AxelCreations** [comment]
Indicar si deben cambiarse estos espacios de todas formas.
